# cs231n Python NumPy Tutorial - NumPy
ECE 5831 (2026) - Assignment 2

Source: https://cs231n.github.io/python-numpy-tutorial/

Sections covered: **NumPy, Arrays, Array indexing, Data types, Array math, Broadcasting**.

## NumPy
NumPy is the core library for scientific computing in Python. It provides a fast
multidimensional array object (`ndarray`) and tools for working with these arrays.

In [1]:
import sys
import numpy as np

print("Python:", sys.version.split()[0])
print("NumPy :", np.__version__)

Python: 3.12.14
NumPy : 2.4.6


## Arrays
A NumPy array is a grid of values, all of the same type, indexed by a tuple of
non-negative integers. The number of dimensions is the **rank** of the array; the
**shape** is a tuple of integers giving the size of the array along each dimension.
Arrays can be initialized from nested Python lists and accessed with square brackets.

In [2]:
a = np.array([1, 2, 3])   # rank 1 array
print(type(a))            # <class 'numpy.ndarray'>
print(a.shape)            # (3,)
print(a[0], a[1], a[2])   # 1 2 3
a[0] = 5                  # change an element of the array
print(a)                  # [5 2 3]

b = np.array([[1, 2, 3], [4, 5, 6]])   # rank 2 array
print(b.shape)                         # (2, 3)
print(b[0, 0], b[0, 1], b[1, 0])       # 1 2 4

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


NumPy also provides many functions to create arrays:

In [3]:
a = np.zeros((2, 2))        # array of all zeros
print(a)

b = np.ones((1, 2))         # array of all ones
print(b)

c = np.full((2, 2), 7)      # constant array
print(c)

d = np.eye(2)               # 2x2 identity matrix
print(d)

e = np.random.random((2, 2))  # array filled with random values in [0, 1)
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.28184823 0.40719735]
 [0.48184401 0.82921564]]


A few more ways to create and inspect arrays:

In [4]:
r = np.arange(10)                 # like Python's range, but returns an array
print(r)
print(np.linspace(0, 1, 5))       # 5 evenly spaced values from 0 to 1
m = r.reshape(2, 5)               # same data viewed with a new shape
print(m)
print("ndim:", m.ndim, "| shape:", m.shape, "| size:", m.size)

[0 1 2 3 4 5 6 7 8 9]
[0.   0.25 0.5  0.75 1.  ]
[[0 1 2 3 4]
 [5 6 7 8 9]]
ndim: 2 | shape: (2, 5) | size: 10


## Array indexing
NumPy offers several ways to index into arrays.

### Slicing
Similar to Python lists, NumPy arrays can be sliced. Since arrays may be
multidimensional, a slice must be given for each dimension.

In [5]:
# rank 2 array with shape (3, 4)
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# first 2 rows and columns 1 and 2 -> b has shape (2, 2)
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


A slice of an array is a **view** into the same data, so modifying it modifies the original array.

In [6]:
print(a[0, 1])   # 2
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # 77

2
77


Integer indexing can be mixed with slice indexing. Doing so yields an array of
**lower rank** than the original array.

In [7]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# two ways of accessing the middle row:
row_r1 = a[1, :]      # rank 1 view of the second row
row_r2 = a[1:2, :]    # rank 2 view of the second row
print(row_r1, row_r1.shape)   # [5 6 7 8] (4,)
print(row_r2, row_r2.shape)   # [[5 6 7 8]] (1, 4)

# the same distinction applies to columns:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)   # [ 2  6 10] (3,)
print(col_r2, col_r2.shape)   # [[ 2] [ 6] [10]] (3, 1)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


### Integer array indexing
Slicing always produces a view of the original array. Integer array indexing lets
you construct **arbitrary** arrays using the data from another array.

In [8]:
a = np.array([[1, 2], [3, 4], [5, 6]])

# an example of integer array indexing; the result has shape (3,)
print(a[[0, 1, 2], [0, 1, 0]])                 # [1 4 5]

# equivalent to:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))   # [1 4 5]

# the same element can be reused
print(a[[0, 0], [1, 1]])                       # [2 2]

# equivalent to:
print(np.array([a[0, 1], a[0, 1]]))            # [2 2]

[1 4 5]
[1 4 5]
[2 2]
[2 2]


A useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [9]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(a)

b = np.array([0, 2, 0, 1])          # array of column indices, one per row

print(a[np.arange(4), b])           # [ 1  6  7 11]

a[np.arange(4), b] += 10            # mutate one element from each row
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


### Boolean array indexing
Boolean array indexing picks out arbitrary elements of an array. It is often used
to select the elements that satisfy some condition.

In [10]:
a = np.array([[1, 2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # boolean array of the same shape as a
print(bool_idx)

# boolean array indexing builds a rank 1 array of the elements where bool_idx is True
print(a[bool_idx])   # [3 4 5 6]

# the same thing in a single statement
print(a[a > 2])      # [3 4 5 6]

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


Boolean masks can be combined with `&` / `|` and used for assignment:

In [11]:
x = np.arange(10)
print(x[(x > 2) & (x % 2 == 0)])   # even numbers greater than 2
x[x > 6] = 0                       # set every element above 6 to 0
print(x)

[4 6 8]
[0 1 2 3 4 5 6 0 0 0]


## Data types
Every NumPy array is a grid of elements of the same type. NumPy guesses a datatype
when an array is created, and array-constructing functions also accept an optional
argument to specify the datatype explicitly.

In [12]:
x = np.array([1, 2])                   # let NumPy choose the datatype
print(x.dtype)                         # int64

x = np.array([1.0, 2.0])               # let NumPy choose the datatype
print(x.dtype)                         # float64

x = np.array([1, 2], dtype=np.int64)   # force a particular datatype
print(x.dtype)                         # int64

int64
float64
int64


Converting between types with `astype`, and the memory used per element:

In [13]:
f = np.array([1.7, 2.2, -3.9])
print(f.astype(np.int32))                  # truncates toward zero
print(np.array([1, 0, 2]).astype(bool))
for dt in (np.int8, np.int32, np.float32, np.float64):
    print(np.dtype(dt).name, "->", np.dtype(dt).itemsize, "bytes per element")

[ 1  2 -3]
[ True False  True]
int8 -> 1 bytes per element
int32 -> 4 bytes per element
float32 -> 4 bytes per element
float64 -> 8 bytes per element


## Array math
Basic mathematical functions operate **elementwise** on arrays and are available both
as operator overloads and as functions in the NumPy module.

In [14]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

# elementwise sum
print(x + y)
print(np.add(x, y))

# elementwise difference
print(x - y)
print(np.subtract(x, y))

# elementwise product
print(x * y)
print(np.multiply(x, y))

# elementwise division
print(x / y)
print(np.divide(x, y))

# elementwise square root
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


Unlike MATLAB, `*` is elementwise multiplication, not matrix multiplication.
`dot` (or the `@` operator) computes inner products of vectors, multiplies a vector
by a matrix, and multiplies matrices.

In [15]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

# inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))
print(v @ w)

# matrix / vector product; all produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

# matrix / matrix product; all produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

219
219
219
[29 67]
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


`sum` can add all elements, or sum along an axis:

In [16]:
x = np.array([[1, 2], [3, 4]])

print(np.sum(x))           # sum of all elements: 10
print(np.sum(x, axis=0))   # sum of each column: [4 6]
print(np.sum(x, axis=1))   # sum of each row: [3 7]

10
[4 6]
[3 7]


Other reductions work the same way:

In [17]:
x = np.array([[1, 2], [3, 4]])
print("mean:", x.mean(), "| max per column:", x.max(axis=0), "| argmin per row:", x.argmin(axis=1))

mean: 2.5 | max per column: [3 4] | argmin per row: [0 0]


Apart from computing with arrays, we frequently need to reshape or otherwise
manipulate data. The simplest example is transposing a matrix with the `T` attribute.

In [18]:
x = np.array([[1, 2], [3, 4]])
print(x)
print(x.T)

# transposing a rank 1 array does nothing
v = np.array([1, 2, 3])
print(v)
print(v.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


## Broadcasting
Broadcasting allows NumPy to work with arrays of different shapes when performing
arithmetic. Frequently we have a smaller array and a larger array, and want to use
the smaller array multiple times to perform some operation on the larger array.

Example: add a constant vector to each row of a matrix. First, with an explicit loop:

In [19]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # empty matrix with the same shape as x

# add v to each row of x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


For a large matrix a Python loop is slow. Stacking copies of `v` with `np.tile` and adding elementwise gives the same result:

In [20]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])

vv = np.tile(v, (4, 1))   # stack 4 copies of v on top of each other
print(vv)

y = x + vv                # add x and vv elementwise
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Broadcasting performs this computation **without actually creating** multiple copies of `v`:

In [21]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])

y = x + v   # add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


The rules for broadcasting two arrays together:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are *compatible* in a dimension if they have the same size in that dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if its shape were the elementwise maximum of the two input shapes.
5. In any dimension where one array had size 1 and the other had size greater than 1, the first array behaves as if it were copied along that dimension.

Some applications of broadcasting:

In [22]:
# outer product of vectors
v = np.array([1, 2, 3])   # shape (3,)
w = np.array([4, 5])      # shape (2,)
# reshape v to a column vector of shape (3, 1); broadcasting it against w
# gives an output of shape (3, 2), the outer product of v and w
print(np.reshape(v, (3, 1)) * w)

# add a vector to each row of a matrix
x = np.array([[1, 2, 3], [4, 5, 6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3)
print(x + v)

# add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# Transposing x gives shape (3, 2), which broadcasts against w to (3, 2);
# transposing the result gives the final shape (2, 3)
print((x.T + w).T)
# another solution: reshape w into a column vector of shape (2, 1)
print(x + np.reshape(w, (2, 1)))

# multiply a matrix by a constant: a scalar is treated as an array of shape ()
print(x * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


Checking the rules: shapes that are not compatible raise an error.

In [23]:
a = np.ones((2, 3))
for other in (np.ones(3), np.ones((2, 1)), np.ones(2)):
    try:
        print(a.shape, "+", other.shape, "->", (a + other).shape)
    except ValueError as err:
        print(a.shape, "+", other.shape, "-> error:", err)

(2, 3) + (3,) -> (2, 3)
(2, 3) + (2, 1) -> (2, 3)
(2, 3) + (2,) -> error: operands could not be broadcast together with shapes (2,3) (2,) 


Broadcasting is also much faster than an explicit Python loop:

In [24]:
import time

big = np.random.random((200_000, 3))
v = np.array([1.0, 0.0, 1.0])

t0 = time.perf_counter()
loop = np.empty_like(big)
for i in range(big.shape[0]):
    loop[i, :] = big[i, :] + v
t_loop = time.perf_counter() - t0

t0 = time.perf_counter()
bcast = big + v
t_bcast = time.perf_counter() - t0

print("same result:", np.allclose(loop, bcast))
print(f"loop: {t_loop:.4f} s | broadcasting: {t_bcast:.4f} s")

same result: True
loop: 0.9617 s | broadcasting: 0.0065 s


## NumPy Documentation
This covers the essentials of NumPy from the tutorial. The full reference is at
https://numpy.org/doc/stable/reference/